### PR TITLE
fix: update dependencies, including jest

### LINKED ISSUE #319: Support Jest 29 to use new conditional directives support for elements other than template
#### Issue 1
Unable to run my tests with Jest v29 and latest v2.0.0 version of sfdx-lwc-jest (attached the error below), The only workaround is to use v1.1.3 where the jest was upgraded to v29 but later it was removed in v1.1.4 because of a breaking change? 

The main reason for my upgrade is because I want the tests to recognize the new conditional directives `lwc:if`,` lwc:else` as the older versions doesn't recognize them and fail the tests.

#### Steps to Reproduce
```bash
# Command to repro
> sfdx-lwc-jest -- --reporters=default --silent XXXX

 FAIL  test/main/default/lwc/XXXX/__tests__/XXXX.test.js
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:63:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        26.092 s
```

#### Issue 2
The other thing i noticed with v1.1.3 when I use the conditional directives on HTML elements or custom elements instead of template throws following error even though deploy was successful and working, I found [this documentation](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.reference_directives) which says we can use the new conditional directives on template and some HTML elements too. Shouldn't that be supported too on other elements or should we keep using template?

```bash
 ● Test suite failed to run
    thrown: [Error: LWC1127: Invalid directive "lwc:else" on element <div>.]
    thrown: [Error: LWC1127: Invalid directive "lwc:else" on element <p>.]
    thrown: [Error: LWC1127: Invalid directive "lwc:if" on element <c-some-custom-lwc>.] 
```

#### Expected Results

Issue 1:  Make @salesforce/sfdx-lwc-jest work with Jest v29

Issue 2: Support use of new conditional directives on HTML and custom elements.

#### Actual Results
Unit tests fail.

### Version

-   @salesforce/sfdx-lwc-jest: v2.0.0
-   Node: v18.15.0

### PR DESCRIPTION
**Pull request by nolanlawson**
BREAKING CHANGE: Jest updated from v27 to v28

Fixes #319

Updates all dependencies, including Jest. Users of `sfdx-lwc-jest` may need to modify their tests to deal with breaking changes in [Jest 28](https://jestjs.io/docs/28.x/upgrading-to-jest28) and [Jest 29](https://jestjs.io/docs/upgrading-to-jest29).

### CODE REVIEW

File: src/log.js [hunk 1]
```diff
@@ -8,14 +8,22 @@
...
-const chalk = require('chalk');
+function blue(message) {
+    // equivalent to chalk.blue()
+    return `\x1B[34m${message}\x1B[39m`;
+}
+
+function red(message) {
+    // equivalent to chalk.red()
+    return `\x1B[31m${message}\x1B[39m`;
+}
```
Comment (nolanlawson) [inline src/log.js:19]: `chalk` has breaking changes, and we don't need it.

**Comment by nolanlawson** [comment]
OK, I tested `lwc-recipes` manually, and it works with this PR. (I wanted to avoid issues we saw with https://github.com/salesforce/sfdx-lwc-jest/issues/288). The above-mentioned issue with `jest-environment-jsdom` is also fixed.

I also tested `--coverage`, and coverage actually works better than before – apparently using `.js` excludes files that are imported with bare file extensions. In the `lwc-recipes` repo, `--coverage` finds many more files than it did previously.

**Review by ekashida — APPROVED** [review]
