### PR TITLE
fix: exclude all node_modules except lightning-stubs

### LINKED ISSUE #75: Test runner performance improvement
## Observation

When running `@salesforce/lwc-jest` against the [receipes](https://github.com/trailheadapps/lwc-recipes) repo in debug mode we can observe that more than half the time during the test run is spent resolving modules. Here is the observed recorded [trace.zip](https://github.com/salesforce/sfdx-lwc-jest/files/3391432/lwc-jest-receipes.zip)

It takes in total 42 seconds to run the tests suite against the receipes repo when running in tests sequentially. When looking at the trace we can observe 2 stops where we spent time resolving LWC modules:
* When the test runner boot up (4.89 sec. / ~10% of the total test run time). https://github.com/salesforce/sfdx-lwc-jest/blob/fbd7c430d5d20ed1e98a0b3899b2234b8364cc46/src/resolver.js#L83
* When jest attempt to resolve a module (22.07 sec. / ~53% of the total test run time): https://github.com/salesforce/sfdx-lwc-jest/blob/fbd7c430d5d20ed1e98a0b3899b2234b8364cc46/src/utils/project.js#L37

We can also notice that the error logging represents around 10% of the total test run time. 

## Steps to reproduce

* `$ npm run test:unit -- --coverage --debug`
* Attach debugger
* Run with pofiler attached

## Environment

* Node: `v10.16.0`
* npm: `v6.9.0`
* @salesforce/lwc-jest: `v0.5.1`

### LINKED ISSUE #107: Out of memory exception when using jest-axe
### Description
I am attempting to use jest-axe, I get a out of memory exception when running the test.

It seems to be related to @lwc/jest-transformer as my simple test case isn't using any LWC and if I comment that out of the jest-config the test no longer an out of memory execption.

#### Steps to Reproduce

```js
// simplified test case
import { axe, toHaveNoViolations } from 'jest-axe';

expect.extend(toHaveNoViolations);

it('Should have no violations', async () => {
    const failingDom = '<img src="#"/>';

    expect(await axe(failingDom)).toHaveNoViolations();
});
```

```js
// Jest config overrides (if any)
const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config');
module.exports = {
    ...jestConfig
};
```

```bash
# Command to repro
lwc-jest
```

#### Expected Results
To get a test failure

#### Actual Results
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Version
- @salesforce/sfdx-lwc-jest: 0.5.4
- Node: 12.9.1

### PR DESCRIPTION
**Pull request by pmdartus**
This PR properly excludes all the `node_modules/` dependencies from being transformed except the lightning-stubs. On top of fixing large file transformation issues, it also greatly improve the overall performance of the test runner (divide by 3 the test during on the [reciepes](https://github.com/trailheadapps/lwc-recipes) repo).

Fix #107, fix #75.

**Note:** This code change will need to be revisited once npm packages distribute components.

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -28,7 +28,9 @@ const jestConfig = {
     transform: {
         '^.+\\.(js|html|css)$': require.resolve('@lwc/jest-transformer')
     },
-    transformIgnorePatterns: ["/node_modules/(?:(?!lightning-stubs.*(js|html|css)))*$"],
+    transformIgnorePatterns: [
```
Comment (ravijayaramappa) [inline src/config.js]: _I don't know if the following is a problem for sfdx-lwc-jest_

If @salesforce/sfdx-lwc-jest is nested inside another node_modules folder like `/node_modules/foo/node_modules/@salesforce/sfdx-lwc-jest/src/lightning-stubs/avatar/avatar.js`, this regex will match and the stubs will not be transformed.

**Comment by pmdartus** [comment]
Now that both @trevor-bliss and @ravijayaramappa are both on PTO. @apapko, @jodarove could you review this PR?
