### PR TITLE
revert(apex-methods-automock): reverts functionality providing apex automocks

### LINKED ISSUE #232: Error when testing parent and child components where child invokes an apex method
### Description
With auto-mock of Apex methods that was introduced and possibly module caching on jest side (https://github.com/facebook/jest/blob/master/packages/jest-resolve/src/resolver.ts#L158) if there is a parent and child component where child calls Apex imperatively mock from parent component will win and child component tests may fail. This occurs only if you run parent component test first and then child component test. If you run them in reverse order, all works fine as child component can mock the module properly.

Also, this caching also causes issues when the same module is imported in multiple unrelated components or when you use service components that only make Apex calls. If two components use the same service and tests are mocking its Apex call, there is a chance that mockResolvedValue or mockRejectedValue will work cross-tests meaning value we want to return in test for cmp1 will be returned in test for cmp2. This one is very hard to reproduce and happens when two test files are processed at the same time, but it is also related to the caching issue as they both share one instance of the mock.

#### Steps to Reproduce
**cmpB (child component)**
```html
<template></template>
```

```js
import { LightningElement, api } from 'lwc';
import myApexAction from '@salesforce/apex/MyApexCtrl.myApexAction';

export default class CmpB extends LightningElement {
    @api
    callApex() {
        myApexAction();
    }
}
```

```js
// cmpB.test.js
import { createElement } from 'lwc';
import myApexAction from '@salesforce/apex/MyApexCtrl.myApexAction';
import CmpB from 'c/cmpB';

jest.mock(
    '@salesforce/apex/MyApexCtrl.myApexAction',
    () => {
        return {
            default: jest.fn()
        };
    },
    { virtual: true }
);

describe('c-cmp-b', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    it('should call myApexAction when callApex called', () => {
        myApexAction.mockResolvedValue();

        const element = createElement('c-cmp-b', {
            is: CmpB
        });

        document.body.appendChild(element);

        element.callApex();

        // Assertion below fails when cmpA tests run before cmpB tests
        expect(myApexAction).toHaveBeenCalledTimes(1);
    });
});
```

**cmpA (parent component)**
```html
<template>
    <c-cmp-b></c-cmp-b>
</template>
```

```js
import { LightningElement } from 'lwc';

export default class CmpA extends LightningElement {}
```

```js
// cmpA.test.js
import { createElement } from 'lwc';
import CmpA from 'c/cmpA';

describe('c-cmp-a', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    it('should render cmpA', () => {
        const element = createElement('c-cmp-a', {
            is: CmpA
        });

        document.body.appendChild(element);
    });
});
```

**Command to reproduce the issue**
```bash
# Running tests in serial mode to easily reproduce the issue
sfdx-lwc-jest -- --runInBand --runTestsByPath ./force-app/main/default/lwc/cmpA/__tests__/cmpA.test.js ./force-app/main/default/lwc/cmpB/__tests__/cmpB.test.js
```

Note: issue happens only if cmpA test runs before cmpB test. I used this sample test sequencer to make sure that's the order:
```js
const Sequencer = require('@jest/test-sequencer').default;

class CustomSequencer extends Sequencer {
    sort(tests) {
        const copyTests = Array.from(tests);
        return copyTests.sort((testA, testB) => (testA.path > testB.path ? 1 : -1));
    }
}

module.exports = CustomSequencer;
```

And then, added this to jest.config.js:
```json
{
    "testSequencer": "<rootDir>/testSequencer.js"
}
```

#### Expected Results

Both tests are passing no matter what's the order.

#### Actual Results

If you run cmpB test first and then cmpA test, they both pass. If you change the order, only cmpA test passes.

### Version

-   @salesforce/sfdx-lwc-jest: 0.12.5
-   Node: 14.3.0

**Additional context/Screenshots**

I tried to use fix that is included in PR: https://github.com/salesforce/sfdx-lwc-jest/pull/231 to see if it fixes the issue as I have also encountered the issue described there, but those two are unrelated. This one seems to be strictly related to the mocks caching and sharing instance of mock between all of the tests.

### PR DESCRIPTION
**Pull request by jodarove**
fixes #232

This PR reverts #231, #210, and #208. They provided functionality to auto mock apex methods.

**Note:** Test authors will need to keep implementing their own apex (+apexContinuation) methods mocks after this PR is merged.

### CODE REVIEW

**Review by pmdartus — APPROVED** [review]

File: src/resolver.js [hunk 1]
```diff
@@ -47,36 +47,20 @@ function resolveAsFile(name, extensions) {
...
 
     if (ns === 'lightning') {
         return getLightningMock(name);
     }
 
-    // See https://developer.salesforce.com/docs/component-library/documentation/en/lwc/reference_salesforce_modules
-    if (
-        modulePath.startsWith('@salesforce/apex/') ||
-        modulePath.startsWith('@salesforce/apexContinuation/')
-    ) {
```
Comment (msrivastav13) [inline src/resolver.js:76]: @jodarove This might be breaking wire adapter mocks as well I guess.
